spring:
  profiles:
    active: dev

---
server:
  port: 8081
spring:
  application:
    name: todolist
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/todolist?useSSL=false&serverTimezone=UTC
    username: root
    password: Yusiheng666666
    type: com.alibaba.druid.pool.DruidDataSource

  jackson:
    default-property-inclusion: non_null # JSON?????????
    time-zone: GMT+8
    date-format: yyyy/M/d H:mm
  config:
    activate:
      on-profile: dev
logging:
  level:
    com.huayu: debug
jasypt:
  encryptor:
    password: huayu
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
---
server:
  port: 8081
spring:
  application:
    name: todolist
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ENC(y62r9gC7N02E6WUdK06/4cYDjlRXh6+nPEI2WSDRjmzEHJJMrfC6NyvOzFHgO4UA9NqUWHfnpRufbNxhxmu9i90i0ajBsZruoR2m5TIzzL+13tuycebINw==)
    username: ENC(mgcFuJ1QOMyJUhbg/e0q6w==)
    password: ENC(Ksn0YYz74h9Y9PRgKDZHIA==)
    type: com.alibaba.druid.pool.DruidDataSource

  jackson:
    default-property-inclusion: non_null # JSON?????????
    time-zone: GMT+8
    date-format: yyyy/M/d H:mm
  config:
    activate:
      on-profile: pro
logging:
  level:
    com.huayu: debug
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator