spring:
  profiles:
    active: dev

---
server:
  port: 8081
spring:
  application:
    name: todolist
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cooperate?useSSL=false&serverTimezone=UTC
    username: root
    password: Yusiheng666666
    type: com.alibaba.druid.pool.DruidDataSource

  jackson:
    default-property-inclusion: non_null # JSON?????????
    time-zone: GMT+8
    date-format: yyyy.M.d HH:mm:ss
  config:
    activate:
      on-profile: dev
logging:
  level:
    com.huayu: debug
jasypt:
  encryptor:
    password: huayu
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
---
server:
  port: 8081
spring:
  application:
    name: todolist
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ENC(GEibUkn+zTcW1PENdgHvXnMjFJba1PJEynEBKKSxpxCakco6W4t7/jXjKcHhAYCgoPVa5plXV2dfIXQDOjANmSgBA7NP7DpPp81DcNxmjZ5H2Di95ypNgQ==)
    username: ENC(66oE4Tlj+cQHjs4cewZScg==)
    password: ENC(VksT58sxx0btWWHNruPM7g==)
    type: com.alibaba.druid.pool.DruidDataSource

  jackson:
    default-property-inclusion: non_null # JSON?????????
    time-zone: GMT+8
    date-format: yyyy.M.d HH:mm:ss
  config:
    activate:
      on-profile: pro
logging:
  level:
    com.huayu: debug
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

